/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_utokyo_vlex_VlexNative */

#ifndef _Included_edu_utokyo_vlex_VlexNative
#define _Included_edu_utokyo_vlex_VlexNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_utokyo_vlex_VlexNative
 * Method:    parse
 * Signature: (Ljava/nio/ByteBuffer;IIILjava/lang/String;ILjava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_edu_utokyo_vlex_VlexNative_parse
  (JNIEnv *, jobject, jobject, jint, jint, jint, jstring, jint, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
